# Generated by Django 6.0 on 2025-12-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FACT_APPROVED', 'Fact Approved'), ('FACT_REJECTED', 'Fact Rejected'), ('VOTE_RECEIVED', 'Received Vote on Fact'), ('VOTE_GIVEN', 'Voted on Fact'), ('BONUS', 'Admin Bonus')], max_length=50)),
                ('score_change', models.IntegerField(help_text='The amount of points added or removed (e.g., +10, -5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_impacts', to='facts.fact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], default='UP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='facts.fact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'fact'], name='reputation__user_id_2f3b9e_idx')],
                'unique_together': {('user', 'fact')},
            },
        ),
    ]
