# Generated by Django 6.0 on 2025-12-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, help_text="Name of the icon from the frontend library (e.g., 'fa-atom')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A concise and catchy title', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField(help_text='Full description of the fact')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('downvotes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='facts.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, help_text="Short description (e.g., 'Article in Nature')", max_length=200)),
                ('is_verified_source', models.BooleanField(default=False, help_text='Indicates if the domain is considered authoritative by the platform')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='facts.fact')),
            ],
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['status', '-created_at'], name='facts_fact_status_d78442_idx'),
        ),
    ]
