# Generated by Django 6.0 on 2025-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to make the fact more engaging.', null=True, upload_to='fact_images/'),
        ),
    ]
